manifest:
  remotes:
    - name: infused-kim
      url-base: https://github.com/infused-kim
  projects:
    - name: zmk
      remote: infused-kim
      revision: my-changes/ext-pwr-usb-only
      import: app/west.yml
  self:
    path: config
